// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public interface DeleteCarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.DeleteCarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 carId = 1;</code>
   */
  int getCarId();
}
