// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public interface GetCarResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetCarResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Car car = 1;</code>
   */
  boolean hasCar();
  /**
   * <code>.proto.Car car = 1;</code>
   */
  proto.Car getCar();
  /**
   * <code>.proto.Car car = 1;</code>
   */
  proto.CarOrBuilder getCarOrBuilder();
}
