// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public interface ListCarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ListCarRequest)
    com.google.protobuf.MessageOrBuilder {
}
