// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public interface ListCarResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ListCarResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Car car = 1;</code>
   */
  java.util.List<proto.Car> 
      getCarList();
  /**
   * <code>repeated .proto.Car car = 1;</code>
   */
  proto.Car getCar(int index);
  /**
   * <code>repeated .proto.Car car = 1;</code>
   */
  int getCarCount();
  /**
   * <code>repeated .proto.Car car = 1;</code>
   */
  java.util.List<? extends proto.CarOrBuilder> 
      getCarOrBuilderList();
  /**
   * <code>repeated .proto.Car car = 1;</code>
   */
  proto.CarOrBuilder getCarOrBuilder(
      int index);
}
